### ISSUE TITLE
zlib_deflated_raw 编码器并不能用

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/AwesomeEncoder#1]
![image](https://user-images.githubusercontent.com/46088090/57826668-e0d0d580-77d6-11e9-80ff-e92b69aa4119.png)

![image](https://user-images.githubusercontent.com/46088090/57826678-e9c1a700-77d6-11e9-89c7-05f2e6c93142.png)
![image](https://user-images.githubusercontent.com/46088090/57826690-f7772c80-77d6-11e9-943e-dd450d25bb66.png)

加不加base64都一样  没返回
PHP 5.6

**Comment by Medicean** [comment]
你肯定是得先确定一下服务端支持zlib扩展

```
var_dump(function_exist('gzinflate'));
```

**Comment by Medicean** [comment]
你肯定是得先确定一下服务端支持zlib扩展

```
var_dump(function_exist('gzinflate'));
```

**Comment by yzddmr6** [comment]
默认都是开启的啊
![image](https://user-images.githubusercontent.com/46088090/57827659-b5e88080-77da-11e9-91e1-da27a04862b8.png)

**Comment by Medicean** [comment]
哦对，你是 windows 下的，windows 下你把 multipart 打开就行了。具体不知道为什么

**Comment by yzddmr6** [comment]
改成这样就好了
`data[randomID] = zlib.deflateRawSync(data['_']).toString('base64');`
把它base64一次

应该是url编码的锅,我写过一个随机异或免杀D盾的脚本,fuzz的过程中发现有些字符是url编码不了的
gzin压缩应该也是一样
上个对比图,这是开启multipart后的

![1](https://user-images.githubusercontent.com/46088090/57837511-8d21b480-77f5-11e9-89d8-1aa99c3e7352.png)

这是不开启的
![2](https://user-images.githubusercontent.com/46088090/57837534-94e15900-77f5-11e9-83e4-af23ee7d8ee7.png)


base64编码就可以完美解决这个问题

![image](https://user-images.githubusercontent.com/46088090/57837646-cc500580-77f5-11e9-870e-1b1cbb5b333f.png)

**Comment by yzddmr6** [comment]
pwd的一句改成
`  data[pwd] = zlib.deflateRawSync(`@eval(@gzinflate(base64_decode($_POST[${randomID}])));`).toString('base64');`

**Comment by Medicean** [comment]
good job!
